# Generated by Django 5.1.2 on 2024-10-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задолженность'),
        ),
    ]
