# Generated by Django 5.1.2 on 2024-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_alter_element_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='element', to='electronics.product', verbose_name='Продукты'),
        ),
    ]
