# Generated by Django 5.1.2 on 2024-10-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_alter_element_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
